name: Deploy Tiquettes website

on:
  push:
    branches: ['dev']

  workflow_dispatch:

jobs:
  web-deploy:
    name: Web Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build web
        run: npm run build:web
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "${{ secrets.FTPSERVER }}"
          username: "${{ secrets.FTPUSERNAME }}"
          password: "${{ secrets.FTPPASSWORD }}"
          protocol: ${{ secrets.FTPPROTOCOL }}
          port: ${{ secrets.FTPPORT }}
          local-dir: "./dist/"
          server-dir: "./app/"